### ISSUE TITLE
Out-of-the-box instructions fail; NoSuchMethodError

### ISSUE THREAD

**Issue by jadekler** [census-instrumentation/opencensus-java#1090]
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?

```
    <dependency>
      <groupId>io.opencensus</groupId>
      <artifactId>opencensus-api</artifactId>
      <version>0.12.2</version>
    </dependency>
    <dependency>
      <groupId>io.opencensus</groupId>
      <artifactId>opencensus-exporter-stats-stackdriver</artifactId>
      <version>0.12.2</version>
    </dependency>
    <dependency>
      <groupId>io.opencensus</groupId>
      <artifactId>opencensus-impl</artifactId>
      <version>0.12.2</version>
      <scope>runtime</scope>
    </dependency>
```

### What JVM are you using (`java -version`)?

```
$ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

### What did you do?

I ran the stats program listed at `Hello "OpenCensus" stats events` in `README.md`, with the following `main()`:

```
public static void main(String[] args) throws IOException {
    StackdriverStatsExporter.createAndRegister(
        StackdriverStatsConfiguration.builder().setProjectId("MyStackdriverProjectId").build());

    Quickstart.initialize();
    Quickstart.processVideo();
    Quickstart.printStats();
  }
```

### What did you expect to see?

A working program.

### What did you see instead?

The following errors:

```
Recorded stats for my.org/views/video_size:
 ViewData{view=View{name=Name{asString=my.org/views/video_size}, description=processed video size over time, measure=MeasureLong{name=my.org/measure/video_size, description=size of processed videos, unit=By}, aggregation=Distribution{bucketBoundaries=BucketBoundaries{boundaries=[0.0, 256.0, 65536.0]}}, columns=[TagKey{name=my.org/keys/frontend}], window=Cumulative{}}, aggregationMap={}, windowData=CumulativeData{start=Timestamp{seconds=1522073905, nanos=213000000}, end=Timestamp{seconds=1522073905, nanos=224000000}}}
Mar 26, 2018 4:18:28 PM io.opencensus.exporter.stats.stackdriver.StackdriverExporterWorker registerView
WARNING: Exception thrown when creating MetricDescriptor.
java.lang.NoSuchMethodError: com.google.common.base.Throwables.throwIfInstanceOf(Ljava/lang/Throwable;Ljava/lang/Class;)V
	at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:54)
	at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
	at com.google.cloud.monitoring.v3.MetricServiceClient.createMetricDescriptor(MetricServiceClient.java:601)
	at io.opencensus.exporter.stats.stackdriver.StackdriverExporterWorker.registerView(StackdriverExporterWorker.java:134)
	at io.opencensus.exporter.stats.stackdriver.StackdriverExporterWorker.export(StackdriverExporterWorker.java:161)
	at io.opencensus.exporter.stats.stackdriver.StackdriverExporterWorker.run(StackdriverExporterWorker.java:209)
	at java.lang.Thread.run(Thread.java:748)

[WARNING] thread Thread[threadDeathWatcher-1-1,1,jean.opencensus.Main] was interrupted but is still alive after waiting at least 15000msecs
[WARNING] thread Thread[threadDeathWatcher-1-1,1,jean.opencensus.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[OpenCensus.Disruptor-0,5,jean.opencensus.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-worker-ELG-2-1,5,jean.opencensus.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-executor-0,5,jean.opencensus.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-worker-ELG-2-2,5,jean.opencensus.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[Thread-1,5,jean.opencensus.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-worker-ELG-2-3,5,jean.opencensus.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[Thread-2,5,jean.opencensus.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[Thread-3,5,jean.opencensus.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[Thread-4,5,jean.opencensus.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-worker-ELG-2-4,5,jean.opencensus.Main] will linger despite being asked to die via interruption
[WARNING] NOTE: 11 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=jean.opencensus.Main,maxpri=10]
java.lang.IllegalThreadStateException
    at java.lang.ThreadGroup.destroy (ThreadGroup.java:778)
    at org.codehaus.mojo.exec.ExecJavaMojo.execute (ExecJavaMojo.java:321)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
```

**Comment by jadekler** [comment]
I believe this is related to https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2710, and that as in that thread `guava` is required. However, unlike that thread, I have no other dependencies. Does opencensus not come with `guava` out the box?

**Comment by songy23** [comment]
@jadekler Thanks for reporting this. OpenCensus has `guava` out the box, but our `guava` is pretty outdated ([19.0](https://github.com/census-instrumentation/opencensus-java/blob/master/build.gradle#L158)), while `com.google.common.base.Throwables.throwIfInstanceOf` is added in `guava` 20.0.

I'll post a PR to fix this.
