### ISSUE TITLE
Investigate the build failures of contrib/agent under JDK 1.6 when updating dependencies.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-java#1333]
Related to https://github.com/census-instrumentation/opencensus-java/pull/1328.

**Comment by elharo** [comment]
Any details on what failed?

**Comment by songy23** [comment]
Only with JDK 1.6:
```bash
io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT > execute STANDARD_ERROR
    Exception in thread "pool-1-thread-1" java.lang.UnsupportedClassVersionError: com/google/common/collect/ImmutableList : Unsupported major.minor version 51.0
    	at java.lang.ClassLoader.defineClass1(Native Method)
    	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    	at com.google.common.truth.FailureMetadata.forFailureStrategy(FailureMetadata.java:47)
    	at com.google.common.truth.StandardSubjectBuilder.forCustomFailureStrategy(StandardSubjectBuilder.java:60)
    	at com.google.common.truth.Truth.<clinit>(Truth.java:116)
    	at io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT$1.run(ExecutorInstrumentationIT.java:72)
    	at io.grpc.Context$1.run(Context.java:592)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    	at java.lang.Thread.run(Thread.java:662)
io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT > execute FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:811)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:969)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1281)
        at java.util.concurrent.Semaphore.acquire(Semaphore.java:286)
        at io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT.execute(ExecutorInstrumentationIT.java:79)
io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT > submit_RunnableWithResult FAILED
    java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class com.google.common.truth.Truth
        at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:222)
        at java.util.concurrent.FutureTask.get(FutureTask.java:83)
        at io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT.submit_RunnableWithResult(ExecutorInstrumentationIT.java:155)
        Caused by:
        java.lang.NoClassDefFoundError: Could not initialize class com.google.common.truth.Truth
            at io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT$4.run(ExecutorInstrumentationIT.java:146)
io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT > submit_Callable FAILED
    java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class com.google.common.truth.Truth
        at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:222)
        at java.util.concurrent.FutureTask.get(FutureTask.java:83)
        at io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT.submit_Callable(ExecutorInstrumentationIT.java:103)
        Caused by:
        java.lang.NoClassDefFoundError: Could not initialize class com.google.common.truth.Truth
            at io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT$2.call(ExecutorInstrumentationIT.java:95)
            at io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT$2.call(ExecutorInstrumentationIT.java:92)
io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT > submit_Runnable FAILED
    java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class com.google.common.truth.Truth
        at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:222)
        at java.util.concurrent.FutureTask.get(FutureTask.java:83)
        at io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT.submit_Runnable(ExecutorInstrumentationIT.java:127)
        Caused by:
        java.lang.NoClassDefFoundError: Could not initialize class com.google.common.truth.Truth
            at io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT$3.run(ExecutorInstrumentationIT.java:121)
io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT > currentContextExecutor STANDARD_ERROR
    Exception in thread "pool-5-thread-1" java.lang.NoClassDefFoundError: Could not initialize class com.google.common.truth.Truth
    	at io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT$5.run(ExecutorInstrumentationIT.java:173)
    	at io.grpc.Context$1.run(Context.java:592)
    	at io.grpc.Context$1.run(Context.java:592)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    	at java.lang.Thread.run(Thread.java:662)
io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT > currentContextExecutor FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:811)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:969)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1281)
        at java.util.concurrent.Semaphore.acquire(Semaphore.java:286)
        at io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT.currentContextExecutor(ExecutorInstrumentationIT.java:193)
io.opencensus.contrib.agent.instrumentation.ThreadInstrumentationIT > start_Runnable STANDARD_ERROR
    Exception in thread "Thread-5" java.lang.NoClassDefFoundError: Could not initialize class com.google.common.truth.Truth
    	at io.opencensus.contrib.agent.instrumentation.ThreadInstrumentationIT$1.run(ThreadInstrumentationIT.java:59)
    	at java.lang.Thread.run(Thread.java:662)
io.opencensus.contrib.agent.instrumentation.ThreadInstrumentationIT > start_Runnable FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.google.common.truth.Truth
        at io.opencensus.contrib.agent.instrumentation.ThreadInstrumentationIT.start_Runnable(ThreadInstrumentationIT.java:69)
io.opencensus.contrib.agent.instrumentation.ThreadInstrumentationIT > start_automaticallyWrappedRunnable STANDARD_ERROR
    Exception in thread "Thread-6" java.lang.NoClassDefFoundError: Could not initialize class com.google.common.truth.Truth
    	at io.opencensus.contrib.agent.instrumentation.ThreadInstrumentationIT$3.run(ThreadInstrumentationIT.java:135)
    	at io.grpc.Context$1.run(Context.java:592)
    	at java.lang.Thread.run(Thread.java:662)
io.opencensus.contrib.agent.instrumentation.ThreadInstrumentationIT > start_automaticallyWrappedRunnable FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.google.common.truth.Truth
        at io.opencensus.contrib.agent.instrumentation.ThreadInstrumentationIT.start_automaticallyWrappedRunnable(ThreadInstrumentationIT.java:141)
io.opencensus.contrib.agent.instrumentation.ThreadInstrumentationIT > start_Subclass STANDARD_ERROR
    Exception in thread "Thread-7" java.lang.NoClassDefFoundError: Could not initialize class com.google.common.truth.Truth
    	at io.opencensus.contrib.agent.instrumentation.ThreadInstrumentationIT$1MyThread.run(ThreadInstrumentationIT.java:83)
io.opencensus.contrib.agent.instrumentation.ThreadInstrumentationIT > start_Subclass FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.google.common.truth.Truth
        at io.opencensus.contrib.agent.instrumentation.ThreadInstrumentationIT.start_Subclass(ThreadInstrumentationIT.java:94)
io.opencensus.contrib.agent.instrumentation.UrlInstrumentationIT > classMethod FAILED
    java.util.ServiceConfigurationError: Provider io.opencensus.impllite.trace.TraceComponentImplLite could not be instantiated.
        at io.opencensus.internal.Provider.createInstance(Provider.java:46)
        at io.opencensus.trace.Tracing.loadTraceComponent(Tracing.java:107)
        at io.opencensus.trace.Tracing.<clinit>(Tracing.java:37)
        at io.opencensus.contrib.agent.instrumentation.UrlInstrumentationIT.beforeClass(UrlInstrumentationIT.java:52)
        Caused by:
        java.lang.reflect.InvocationTargetException
            at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
            at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
            at io.opencensus.internal.Provider.createInstance(Provider.java:43)
            ... 3 more
            Caused by:
            java.lang.UnsupportedClassVersionError: com/google/common/util/concurrent/MoreExecutors : Unsupported major.minor version 51.0
                at java.lang.ClassLoader.defineClass1(Native Method)
                at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
                at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
                at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
                at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
                at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
                at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
                at java.security.AccessController.doPrivileged(Native Method)
                at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
                at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
                at io.opencensus.implcore.internal.DaemonThreadFactory.<clinit>(DaemonThreadFactory.java:31)
                at io.opencensus.implcore.trace.export.SpanExporterImpl.<init>(SpanExporterImpl.java:87)
                at io.opencensus.implcore.trace.export.SpanExporterImpl.create(SpanExporterImpl.java:55)
                at io.opencensus.implcore.trace.export.ExportComponentImpl.<init>(ExportComponentImpl.java:83)
                at io.opencensus.implcore.trace.export.ExportComponentImpl.createWithoutInProcessStores(ExportComponentImpl.java:73)
                at io.opencensus.implcore.trace.TraceComponentImplBase.<init>(TraceComponentImplBase.java:58)
                at io.opencensus.impllite.trace.TraceComponentImplLite.<init>(TraceComponentImplLite.java:38)
                ... 8 more
io.opencensus.contrib.agent.instrumentation.UrlInstrumentationIT > classMethod FAILED
    java.lang.NoClassDefFoundError: Could not initialize class io.opencensus.trace.Tracing
        at io.opencensus.contrib.agent.instrumentation.UrlInstrumentationIT.afterClass(UrlInstrumentationIT.java:57)
10 tests completed, 10 failed
```

**Comment by songy23** [comment]
Obsolete.
