### ISSUE TITLE
Bring grpc to latest version 1.14

### ISSUE THREAD

**Issue by solatis** [census-instrumentation/opencensus-java#1403]
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?

0.15.1

### What JVM are you using (`java -version`)?

java8

### What did you do?
If possible, provide a recipe for reproducing the error.

Install opencensus in combination with one of the later Google Cloud Java API libraries (e.g. com.google.cloud/google-cloud-logging "1.41.0"). 

### What did you expect to see?

OpenCensus Stackdriver stats exporter library able to load.

### What did you see instead?

```WARNING: Exception thrown when creating MetricDescriptor.
java.lang.NoSuchMethodError: io.grpc.CallOptions$Key.createWithDefault(Ljava/lang/String;Ljava/lang/Object;)Lio/grpc/CallOptions$Key;
        at com.google.api.gax.grpc.CallOptionsUtil.<clinit>(CallOptionsUtil.java:44)
        at com.google.api.gax.grpc.GrpcMetadataHandlerInterceptor.interceptCall(GrpcMetadataHandlerInterceptor.java:58)
        at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
        at io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:736)
        at io.grpc.internal.ForwardingManagedChannel.newCall(ForwardingManagedChannel.java:63)
        at com.google.api.gax.grpc.GrpcClientCalls.newCall(GrpcClientCalls.java:75)
        at com.google.api.gax.grpc.GrpcDirectCallable.futureCall(GrpcDirectCallable.java:58)
        at com.google.api.gax.grpc.GrpcExceptionCallable.futureCall(GrpcExceptionCallable.java:64)
        at com.google.api.gax.rpc.UnaryCallable$1.futureCall(UnaryCallable.java:126)
        at com.google.api.gax.rpc.UnaryCallable.futureCall(UnaryCallable.java:87)
        at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
        at com.google.cloud.monitoring.v3.MetricServiceClient.createMetricDescriptor(MetricServiceClient.java:747)
        at io.opencensus.exporter.stats.stackdriver.StackdriverExporterWorker.registerView(StackdriverExporterWorker.java:137)
        at io.opencensus.exporter.stats.stackdriver.StackdriverExporterWorker.export(StackdriverExporterWorker.java:164)
        at io.opencensus.exporter.stats.stackdriver.StackdriverExporterWorker.run(StackdriverExporterWorker.java:213)
        at java.lang.Thread.run(Thread.java:748)
```

I suspect this is due to the discrepancy between io.grpc versions.

**Comment by solatis** [comment]
I was already doing precisely that, which is when the exception was being thrown. I think what might be going on is a backwards incompatible update in the GRPC library.

**Comment by songy23** [comment]
I see, then can you try the other way around: exclude the shaded `1.12.0` gRPC jar from the transitive dependency of OpenCensus? I think that will resolve the issue temporarily. This issue is likely due to gRPC introduced a new API in 1.14, and the shaded 1.12 gRPC does not have the API.
