### ISSUE TITLE
OcAgentExporter does not work (on windows?)

### ISSUE THREAD

**Issue by lmolkova** [census-instrumentation/opencensus-java#1897]
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?
0.21.0

### What JVM are you using (`java -version`)?
1.8.0_201

### What did you do?
If possible, provide a recipe for reproducing the error.

```java
  public static void main(String[] args) throws Exception {
    TraceConfig traceConfig = Tracing.getTraceConfig();
    traceConfig.updateActiveTraceParams(
        traceConfig.getActiveTraceParams().toBuilder().setSampler(Samplers.alwaysSample()).build());

    Tracer tracer = Tracing.getTracer();
    OcAgentTraceExporter.createAndRegister();
    try (Scope _ = tracer.spanBuilder("tracingExample1").startScopedSpan()) {
    }

    Tracing.getExportComponent().shutdown();
  }
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>deleteme</groupId>
  <artifactId>deleteme</artifactId>
  <version>1.0-SNAPSHOT</version>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>7</source>
          <target>7</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <dependencies>
    <dependency>
      <groupId>io.opencensus</groupId>
      <artifactId>opencensus-api</artifactId>
      <version>0.21.0</version>
    </dependency>
    <dependency>
      <groupId>io.opencensus</groupId>
      <artifactId>opencensus-exporter-trace-ocagent</artifactId>
      <version>0.21.0</version>
    </dependency>
    <dependency>
      <groupId>io.opencensus</groupId>
      <artifactId>opencensus-impl</artifactId>
      <version>0.21.0</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>

</project>
```

### What did you expect to see?
Spans are exported

### What did you see instead?

Bunch of exceptions in the log, no data is exported
```
WARNING: Exception thrown by the service export io.opencensus.exporter.trace.ocagent.OcAgentTraceExporter
java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
```

```
May 13, 2019 4:40:40 PM io.grpc.netty.GrpcSslContexts defaultSslProvider
INFO: netty-tcnative unavailable (this may be normal)
java.lang.ClassNotFoundException: io.netty.internal.tcnative.SSL
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:81)
	at io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:244)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
	at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
	at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:401)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:444)
	at io.opencensus.exporter.trace.ocagent.OcAgentTraceExporterHandler.getTraceServiceStub(OcAgentTraceExporterHandler.java:135)
	at io.opencensus.exporter.trace.ocagent.OcAgentTraceExporterHandler.export(OcAgentTraceExporterHandler.java:88)
	at io.opencensus.implcore.trace.export.SpanExporterImpl$Worker.onBatchExport(SpanExporterImpl.java:147)
	at io.opencensus.implcore.trace.export.SpanExporterImpl$Worker.run(SpanExporterImpl.java:196)
	at java.lang.Thread.run(Thread.java:748)

May 13, 2019 4:40:40 PM io.grpc.netty.GrpcSslContexts defaultSslProvider
INFO: Conscrypt not found (this may be normal)
May 13, 2019 4:40:40 PM io.grpc.netty.GrpcSslContexts defaultSslProvider
INFO: Jetty ALPN unavailable (this may be normal)
java.lang.ClassNotFoundException: org/eclipse/jetty/alpn/ALPN
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at io.grpc.netty.JettyTlsUtil.isJettyAlpnConfigured(JettyTlsUtil.java:64)
	at io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:266)
	at io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:248)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
	at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
	at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:401)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:444)
	at io.opencensus.exporter.trace.ocagent.OcAgentTraceExporterHandler.getTraceServiceStub(OcAgentTraceExporterHandler.java:135)
	at io.opencensus.exporter.trace.ocagent.OcAgentTraceExporterHandler.export(OcAgentTraceExporterHandler.java:88)
	at io.opencensus.implcore.trace.export.SpanExporterImpl$Worker.onBatchExport(SpanExporterImpl.java:147)
	at io.opencensus.implcore.trace.export.SpanExporterImpl$Worker.run(SpanExporterImpl.java:196)
	at java.lang.Thread.run(Thread.java:748)

May 13, 2019 4:40:40 PM io.opencensus.implcore.trace.export.SpanExporterImpl$Worker onBatchExport
WARNING: Exception thrown by the service export io.opencensus.exporter.trace.ocagent.OcAgentTraceExporter
java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
	at io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:258)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
	at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
	at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:401)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:444)
	at io.opencensus.exporter.trace.ocagent.OcAgentTraceExporterHandler.getTraceServiceStub(OcAgentTraceExporterHandler.java:135)
	at io.opencensus.exporter.trace.ocagent.OcAgentTraceExporterHandler.export(OcAgentTraceExporterHandler.java:88)
	at io.opencensus.implcore.trace.export.SpanExporterImpl$Worker.onBatchExport(SpanExporterImpl.java:147)
	at io.opencensus.implcore.trace.export.SpanExporterImpl$Worker.run(SpanExporterImpl.java:196)
	at java.lang.Thread.run(Thread.java:748)

May 13, 2019 4:40:44 PM io.grpc.netty.GrpcSslContexts defaultSslProvider
INFO: netty-tcnative unavailable (this may be normal)
java.lang.ClassNotFoundException: io.netty.internal.tcnative.SSL
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:81)
	at io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:244)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
	at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
	at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:401)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:444)
	at io.opencensus.exporter.trace.ocagent.OcAgentTraceExporterHandler.getTraceServiceStub(OcAgentTraceExporterHandler.java:135)
	at io.opencensus.exporter.trace.ocagent.OcAgentTraceExporterHandler.export(OcAgentTraceExporterHandler.java:88)
	at io.opencensus.implcore.trace.export.SpanExporterImpl$Worker.onBatchExport(SpanExporterImpl.java:147)
	at io.opencensus.implcore.trace.export.SpanExporterImpl$Worker.run(SpanExporterImpl.java:196)
	at java.lang.Thread.run(Thread.java:748)

May 13, 2019 4:40:44 PM io.grpc.netty.GrpcSslContexts defaultSslProvider
INFO: Conscrypt not found (this may be normal)
May 13, 2019 4:40:44 PM io.grpc.netty.GrpcSslContexts defaultSslProvider
INFO: Jetty ALPN unavailable (this may be normal)
java.lang.ClassNotFoundException: org/eclipse/jetty/alpn/ALPN
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at io.grpc.netty.JettyTlsUtil.isJettyAlpnConfigured(JettyTlsUtil.java:64)
	at io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:266)
	at io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:248)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
	at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
	at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:401)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:444)
	at io.opencensus.exporter.trace.ocagent.OcAgentTraceExporterHandler.getTraceServiceStub(OcAgentTraceExporterHandler.java:135)
	at io.opencensus.exporter.trace.ocagent.OcAgentTraceExporterHandler.export(OcAgentTraceExporterHandler.java:88)
	at io.opencensus.implcore.trace.export.SpanExporterImpl$Worker.onBatchExport(SpanExporterImpl.java:147)
	at io.opencensus.implcore.trace.export.SpanExporterImpl$Worker.flush(SpanExporterImpl.java:210)
	at io.opencensus.implcore.trace.export.SpanExporterImpl.flush(SpanExporterImpl.java:78)
	at io.opencensus.implcore.trace.export.SpanExporterImpl.shutdown(SpanExporterImpl.java:82)
	at io.opencensus.implcore.trace.export.ExportComponentImpl.shutdown(ExportComponentImpl.java:53)
	at Program.main(Program.java:30)

May 13, 2019 4:40:44 PM io.opencensus.implcore.trace.export.SpanExporterImpl$Worker onBatchExport
WARNING: Exception thrown by the service export io.opencensus.exporter.trace.ocagent.OcAgentTraceExporter
java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
	at io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:258)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
	at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
	at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:401)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:444)
	at io.opencensus.exporter.trace.ocagent.OcAgentTraceExporterHandler.getTraceServiceStub(OcAgentTraceExporterHandler.java:135)
	at io.opencensus.exporter.trace.ocagent.OcAgentTraceExporterHandler.export(OcAgentTraceExporterHandler.java:88)
	at io.opencensus.implcore.trace.export.SpanExporterImpl$Worker.onBatchExport(SpanExporterImpl.java:147)
	at io.opencensus.implcore.trace.export.SpanExporterImpl$Worker.flush(SpanExporterImpl.java:210)
	at io.opencensus.implcore.trace.export.SpanExporterImpl.flush(SpanExporterImpl.java:78)
	at io.opencensus.implcore.trace.export.SpanExporterImpl.shutdown(SpanExporterImpl.java:82)
	at io.opencensus.implcore.trace.export.ExportComponentImpl.shutdown(ExportComponentImpl.java:53)
	at Program.main(Program.java:30)
```

### Additional context
This is windows, am I missing some dependencies?

**Comment by songy23** [comment]
> am I missing some dependencies?

I think so. Adding a runtime dependency on `io.netty:netty-tcnative-boringssl-static` should resolve this. Refer to the pom file in examples: https://github.com/census-instrumentation/opencensus-java/blob/463809643f286df925a0b4f5e469ac29096ac945/examples/pom.xml#L126-L131.

**Comment by lmolkova** [comment]
2.0.8 didn't help, but with 2.0.20 it works just fine, thanks a lot!

```xml
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <version>2.0.20.Final</version>
      <scope>runtime</scope>
    </dependency>
```

Is there a way to automatically pull it conditionally depending on the os?

**Comment by songy23** [comment]
> Is there a way to automatically pull it conditionally depending on the os?

I'm not sure, though I think this dependency should always be added regardless of OS (it's also required on Linux/MacOS).

**Comment by lmolkova** [comment]
It seems issue with 2.0.8 is something else, 2.0.8 solves all ClassNotFoundException and makes above app work fine.
