### ISSUE TITLE
Binary incompatibility with prometheus java  simpleclient versions 0.11+

### ISSUE THREAD

**Issue by iggyzap** [census-instrumentation/opencensus-java#2079]
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?
0.16.1

### What JVM are you using (`java -version`)?
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11-alpine-r0)
OpenJDK 64-Bit Server VM (build 11.0.9+11-alpine-r0, mixed mode)

### What did you do?
I've instrumented java server while using prometheus simple client version 0.11.0

### What did you expect to see?
No errors

### What did you see instead?
```
Jul 28, 2021 9:38:02 PM io.opencensus.exporter.stats.prometheus.PrometheusStatsCollector describe
WARNING: Exception thrown when describing metrics.
java.lang.NoSuchFieldError: UNTYPED
	at io.opencensus.exporter.stats.prometheus.PrometheusExportUtils.<clinit>(PrometheusExportUtils.java:91)
	at io.opencensus.exporter.stats.prometheus.PrometheusStatsCollector.describe(PrometheusStatsCollector.java:149)
	at io.prometheus.client.CollectorRegistry.collectorNames(CollectorRegistry.java:98)
	at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:50)
	at io.prometheus.client.Collector.register(Collector.java:193)
	at io.prometheus.client.Collector.register(Collector.java:186)
	at io.opencensus.exporter.stats.prometheus.PrometheusStatsCollector.createAndRegister(PrometheusStatsCollector.java:72)
	at com.hertz.htp.toyota.grpc.ThinClient.run(ThinClient.java:115)
	at com.hertz.htp.toyota.grpc.ThinClient.main(ThinClient.java:266)

```

**Comment by iggyzap** [comment]
Related issue in prometheus tracker: https://github.com/prometheus/client_java/issues/623

**Comment by AdwitiyaMishra** [comment]
Hi, is this issue still available? If yes, I would like to work on it.
