### ISSUE TITLE
Occasional integration test failure in Java 7 Travis build

### ISSUE THREAD

**Issue by sebright** [census-instrumentation/opencensus-java#540]
Here are two examples:

https://travis-ci.org/census-instrumentation/opencensus-java/jobs/267052610
https://travis-ci.org/census-instrumentation/opencensus-java/jobs/265790708

Error message from the first link:

```
:opencensus-agent:integrationTestAug 22, 2017 5:45:08 AM io.opencensus.contrib.agent.AgentMain premain
INFO: Initializing.
Aug 22, 2017 5:45:09 AM io.opencensus.contrib.agent.AgentMain premain
INFO: Initialized.
io.grpc.Context: Storage override doesn't exist. Using default.
java.lang.ClassNotFoundException: io.grpc.override.ContextStorageOverride
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:191)
	at io.grpc.Context.<clinit>(Context.java:132)
	at io.opencensus.contrib.agent.instrumentation.ContextStrategyImpl.wrapInCurrentContext(ContextStrategyImpl.java:54)
	at io.opencensus.contrib.agent.bootstrap.ContextManager.wrapInCurrentContext(ContextManager.java:71)
	at org.gradle.internal.concurrent.StoppableExecutorImpl.execute(StoppableExecutorImpl.java:38)
	at org.gradle.internal.remote.internal.hub.MessageHub.addHandler(MessageHub.java:131)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection.addIncoming(MessageHubBackedObjectConnection.java:80)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.startReceivingTests(TestWorker.java:95)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:66)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:45)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:76)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:34)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:111)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:60)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:62)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:67)
io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationTest > currentContextExecutor FAILED
    java.lang.Exception at ExecutorInstrumentationTest.java:188
8 tests completed, 1 failed
:opencensus-agent:integrationTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':opencensus-agent:integrationTest'.
> There were failing tests. See the report at: file:///home/travis/build/census-instrumentation/opencensus-java/contrib/agent/build/reports/tests/integrationTest/index.html
```

/cc @ubschmidt2

**Comment by ubschmidt2** [comment]
Investigating.

The first logged exception (and the stacktrace) is a red herring. This is because gradle's test runner switches to verbose logging, which triggers verbose logging (to stderr/out) in io.grpc.Context. This behavior has been changed in https://github.com/grpc/grpc-java/pull/3191/files. Version 1.5 of io.grpc.Context should have this change. => going to test with a newer version and send a PR to switch to a newer version of the io.grpc.Context dep.

The second exception is the actual issue:
```
io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationTest > currentContextExecutor FAILED
    java.lang.Exception at ExecutorInstrumentationTest.java:188
```
=> still looking into this. java.lang.Exception at https://github.com/census-instrumentation/opencensus-java/blob/6d8f6e42052ef37a8cc04dc942e1c9df4f48658b/contrib/agent/src/integration-test/java/io/opencensus/contrib/agent/instrumentation/ExecutorInstrumentationTest.java#L188 doesn't yet makes sense to me.

**Comment by ubschmidt2** [comment]
FWIW, I've restarted the build in Travis to get rid of the red build failure image.

**Comment by ubschmidt2** [comment]
It seems that one of the assertions in https://github.com/census-instrumentation/opencensus-java/blob/6d8f6e42052ef37a8cc04dc942e1c9df4f48658b/contrib/agent/src/integration-test/java/io/opencensus/contrib/agent/instrumentation/ExecutorInstrumentationTest.java#L164-L178 fails, but it's only logged to stdout/err by the uncaughtexceptionhandler.

**Comment by ubschmidt2** [comment]
Could be a test timeout, too. Need to use "full" testLogging.exceptionFormat to see this.

Example without testLogging.exceptionFormat:
```none
io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationTest > currentContextExecutor FAILED
    java.lang.Exception at ExecutorInstrumentationTest.java:193
```

Example with exceptionFormat "full":
```none
io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationTest > currentContextExecutor FAILED
    java.lang.Exception: test timed out after 1000 milliseconds
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationTest.currentContextExecutor(ExecutorInstrumentationTest.java:193)
```

**Comment by ubschmidt2** [comment]
https://github.com/census-instrumentation/opencensus-java/pull/541 should add enough details to the Gradle output for failed integration tests.

**Comment by bogdandrutu** [comment]
I always get this error. I would suggest disabling these tests until a fix is submitted

> Task :opencensus-contrib-agent:integrationTest
objc[41887]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java (0x10700f4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1070d74e0). One of the two will be used. Which one is undefined.
Error opening zip file or JAR manifest missing : /Users/bdrutu/github/opencensus-java/contrib/agent/build/libs/opencensus-contrib-agent-0.6.0-SNAPSHOT.jar
Error occurred during initialization of VM
agent library failed to init: instrument
objc[41888]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java (0x1011364c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1031bc4e0). One of the two will be used. Which one is undefined.
Error opening zip file or JAR manifest missing : /Users/bdrutu/github/opencensus-java/contrib/agent/build/libs/opencensus-contrib-agent-0.6.0-SNAPSHOT.jar
Error occurred during initialization of VM
agent library failed to init: instrument
Process 'Gradle Test Executor 17' finished with non-zero exit value 1
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 17' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:370)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.onProcessStop(DefaultWorkerProcess.java:118)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.access$000(DefaultWorkerProcess.java:41)
        at org.gradle.process.internal.worker.DefaultWorkerProcess$1.executionFinished(DefaultWorkerProcess.java:74)
        at sun.reflect.GeneratedMethodAccessor628.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy97.executionFinished(Unknown Source)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:216)
        at org.gradle.process.internal.DefaultExecHandle.finished(DefaultExecHandle.java:315)
        at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:103)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:83)
        at org.gradle.internal.operations.BuildOperationIdentifierPreservingRunnable.run(BuildOperationIdentifierPreservingRunnable.java:39)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)

**Comment by bogdandrutu** [comment]
:opencensus-contrib-agent:integrationTestio.grpc.Context: Storage override doesn't exist. Using default.
java.lang.ClassNotFoundException: io.grpc.override.ContextStorageOverride
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:191)
	at io.grpc.Context.<clinit>(Context.java:132)
	at io.opencensus.contrib.agent.instrumentation.ContextStrategyImpl.wrapInCurrentContext(ContextStrategyImpl.java:57)
	at io.opencensus.contrib.agent.bootstrap.ContextManager.wrapInCurrentContext(ContextManager.java:74)
	at org.gradle.internal.concurrent.StoppableExecutorImpl.execute(StoppableExecutorImpl.java:38)
	at org.gradle.internal.remote.internal.hub.MessageHub.addHandler(MessageHub.java:131)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection.addIncoming(MessageHubBackedObjectConnection.java:80)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.startReceivingTests(TestWorker.java:95)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:66)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:45)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:76)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:34)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:111)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:60)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:62)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:67)
io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT > currentContextExecutor FAILED
    java.lang.Exception: test timed out after 5000 milliseconds
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:503)
        at io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT.currentContextExecutor(ExecutorInstrumentationIT.java:192)
8 tests completed, 1 failed
:opencensus-contrib-agent:integrationTest FAILED
FAILURE: Build failed with an exception.

**Comment by bogdandrutu** [comment]
Last 2 failures were on my local machine (Java8) and travis java8.

**Comment by ubschmidt2** [comment]
The  message/exception from io.grpc.context is expected. Gradle messes with the log level, which results in this message being logged. I can add a workaround for this. In any case, it is totally unrelated to any build failures.

Now as for the actual issue: so far I can see that there is a timeout. Going to ncrease the timeout. I cannot exclude other causes, so please provide more details, maybe even a full -d gradle build output.

**Comment by ubschmidt2** [comment]
Please note that the occasional failures are very different from the permanent failures seen on Bogdan's machine. I'm seeking details on the permanent failures. Does this also happen for a clean build, etc?

**Comment by ubschmidt2** [comment]
Re-focusing this issue on the occasional build failures. Permanent failures are topic of https://github.com/census-instrumentation/opencensus-java/issues/557.

**Comment by sebright** [comment]
I just noticed another failure in a PR that didn't affect the agent code: https://travis-ci.org/census-instrumentation/opencensus-java/jobs/269796141

The error is a timeout:

```
io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT > currentContextExecutor FAILED
    java.lang.Exception: test timed out after 60000 milliseconds
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:503)
        at io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT.currentContextExecutor(ExecutorInstrumentationIT.java:192)
8 tests completed, 1 failed
:opencensus-contrib-agent:integrationTest FAILED
FAILURE: Build failed with an exception.
```

**Comment by bogdandrutu** [comment]
Seen this once:
:opencensus-contrib-agent:shadowJar UP-TO-DATE
:opencensus-contrib-agent:integrationTestio.grpc.Context: Storage override doesn't exist. Using default.
java.lang.ClassNotFoundException: io.grpc.override.ContextStorageOverride
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:191)
	at io.grpc.Context.<clinit>(Context.java:132)
	at io.opencensus.contrib.agent.instrumentation.ContextStrategyImpl.wrapInCurrentContext(ContextStrategyImpl.java:57)
	at io.opencensus.contrib.agent.bootstrap.ContextManager.wrapInCurrentContext(ContextManager.java:74)
	at org.gradle.internal.concurrent.StoppableExecutorImpl.execute(StoppableExecutorImpl.java:38)
	at org.gradle.internal.remote.internal.hub.MessageHub.addHandler(MessageHub.java:131)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection.addIncoming(MessageHubBackedObjectConnection.java:80)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.startReceivingTests(TestWorker.java:95)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:66)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:45)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:76)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:34)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:111)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:60)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:62)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:67)
io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT > currentContextExecutor FAILED
    java.lang.Exception: test timed out after 60000 milliseconds
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:503)
        at io.opencensus.contrib.agent.instrumentation.ExecutorInstrumentationIT.currentContextExecutor(ExecutorInstrumentationIT.java:192)
8 tests completed, 1 failed
:opencensus-contrib-agent:integrationTest FAILED

**Comment by bogdandrutu** [comment]
No longer seen this failure. Should we close this bug?

**Comment by ubschmidt2** [comment]
Thanks! ;-)

**Comment by sebright** [comment]
Reopening, since the error occurred again in #793.

**Comment by ubschmidt2** [comment]
#798 fixes an obvious synchronization issue in the test. I'm closing this for now. Let's reopen if this should surface again.
